### ISSUE TITLE
u can add recorder and effects ?

### ISSUE THREAD

**Issue by odaymusic** [dawg/dawg#177]
# Expected Behavior
What was the expected behavior?

# Current Behavior
What is the current behavior?

# Failure Information (for bugs)
Provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce
Provide detailed steps for reproducing the issue.

1.
2.
3.

## Context
Please provide any relevant information about your setup that might be needed to reproduce the issue.

## Failure Logs or Screenshots
Please include any relevant log snippets, files, or screenshots here.

**Comment by jsmith** [comment]
Hey @odaymusic, do you mind explaining what you are trying to do?

**Comment by jsmith** [comment]
Closing this for now. Let me know if you still have a questions!

**Comment by odaymusic** [comment]
hello sorry for the delay
I want to have an audio recorder + add sound effects to recorded files and
musical instruments.. I have some investors who can support me financially
to produce an integrated music program, but I have to present a good idea
by recording the sound of music and then we are working on developing the
program even further. Works in audio and video
For example this is a multitrack recorder but it does not contain effects
but you can edit some audio steps
https://naomiaro.github.io/waveform-playlist/web-audio-editor.html

**Comment by odaymusic** [comment]
i like this lib for fx https://alemangui.github.io/pizzicato/
