### ISSUE TITLE
Research sentry and see if it can be integrated for error reporting issues during production

### ISSUE THREAD

**Issue by jsmith** [dawg/dawg#18]
As a user, I don't want to have to make bug reports when I am having issues.

In our code, we should catch errors and report them to an online service. This is exactly what [Sentry](https://sentry.io/welcome/) was made for.

See [here](https://github.com/getsentry/sentry-electron) for the official Electron SDK. Although this isn't essential, we want to do this before we put out any releases. Additionally, it should be a pretty good first issue for anyone who wants it.

**Comment by heitorsilva** [comment]
Hi! I got very interested on helping the project, and I think this is a great first task to work on.

Do you have a Sentry account already defined? Can you give me the DSN or share with me the username / password for the Sentry of DAWG?

**Comment by jsmith** [comment]
Hey @heitorsilva, sorry for the slow reply!

Here is the DSN: 
```
https://2390ae0adc0540d0b7efa963d70da3e7@sentry.io/5188927
```

I've never used sentry before today but it seems very slick :) Also excited that you're interested in contributing to this project. Just so you're aware what I'm working on at the moment, I am currently  refactoring the core audio system (currently based on Tone.js) to have zero dependencies (ie. just use the Web Audio API). If there is anything that I can help with let me know :)

**Comment by jsmith** [comment]
Oops try this DSN code actually:
```
https://49cb176e1e5c4728b16631baac74f002@sentry.io/5189007
```

Do you have a sentry account so that I could add you to the team?

**Comment by heitorsilva** [comment]
Yes, I do. Try searching for the email contato@heitorsilva.com

**Comment by jsmith** [comment]
Just submitted an application to get an account as an open source project :) Once I get an account I can add you!

**Comment by jsmith** [comment]
Ok sorry for the delay, but I've added you to the project :) You should be able to access it using [this link](https://sentry.io/organizations/dawg/issues/?project=5189007)!

**Comment by heitorsilva** [comment]
Hey @jsmith! I entered the link and requested to participate on the organization.

Also, can you put me with some kind of permission here in GitHub, so I can take the issue for me? Or, maybe assign me to this issue here?

**Comment by heitorsilva** [comment]
Just saw I had an email on my spam folder, to join Sentry. Now I can work on this... thx ^^

**Comment by jsmith** [comment]
I assigned you this issue but also invited you (with basic permissions for now) to this repo :) Definitely let me know if you have any questions. I'd love to take some time to improve the documentation!

**Comment by heitorsilva** [comment]
@jsmith please, can you go to https://sentry.io/settings/dawg/projects/dawg/ and configure the Allowed Domains box to have only dawg.dev?

**Comment by jsmith** [comment]
Done!

**Comment by heitorsilva** [comment]
@jsmith sorry, but actually, since we run as an Electron App, it's better to leave with the "*" we had before on https://sentry.io/settings/dawg/projects/dawg/. We'll have to think on the security aspect of the DSN later... can you change it back, please?

**Comment by jsmith** [comment]
No worries, just changed it back!

**Comment by heitorsilva** [comment]
Done: https://github.com/dawg/dawg/pull/173

**Comment by jsmith** [comment]
Thanks for your help with this :)
